# Вариант 13 по журналу

In [10]:
import numpy as np

In [11]:
a = [[1,2,3],
     [1,4,2]]

In [12]:
# Четырехмерная матрица
A1 = np.array([[-3., -2., -4., 3.],
              [-2., -4., -5., -5.],
              [0, 2., 2., -4.],
              [-5., 4., 4., 4.]])

B1 = np.array([38., 10., -26., 16.])

In [13]:
A2 = np.array([[-2., -3., 1., -4., -1.],
              [2., 4., -3., -5., 2.],
              [2., 0, -2., -3., 3.],
              [-3., -4., -1., -1., 4.],
              [4., -2., 1., -3., -4.]])

B2 = np.array([25., 32., 30., -23., -16.])

In [14]:
def print_iteration(A,B):
    for i in range(A.shape[0]):
        print(A[i],'|=|',B[i])

In [15]:
print_iteration(A1,B1)

[-3. -2. -4.  3.] |=| 38.0
[-2. -4. -5. -5.] |=| 10.0
[ 0.  2.  2. -4.] |=| -26.0
[-5.  4.  4.  4.] |=| 16.0


In [16]:
def to_triangle(A,B):
    for i in range(A.shape[0] - 1):
        denominator = A[i][i]
        if denominator == 0:
            continue
        A[i] = A[i] / denominator
        B[i] = B[i] / denominator

        for k in range(A.shape[0] - 1, i, -1):
            B[k] = B[k] - A[k][i] * B[i]
            A[k] = A[k] - A[k][i] * A[i]
        print_iteration(A,B)
        print('----------------')
    return A, B


def find_roots(A,B):
    X = [0. for i in range(B.shape[0])]

    for i in range(B.shape[0] - 1, -1, -1):
        X[i] = ((B[i] - sum(X * A[i])) / A[i][i]).round()
    print('Найденные корни:')
    return X


def Gauss_method(A, B):
    triangle_form = to_triangle(A,B)
    return find_roots(triangle_form[0],triangle_form[1])

In [17]:
Gauss_method(A1, B1)

[ 1.          0.66666667  1.33333333 -1.        ] |=| -12.666666666666666
[ 0.         -2.66666667 -2.33333333 -7.        ] |=| -15.333333333333332
[ 0.  2.  2. -4.] |=| -26.0
[ 0.          7.33333333 10.66666667 -1.        ] |=| -47.33333333333333
----------------
[ 1.          0.66666667  1.33333333 -1.        ] |=| -12.666666666666666
[-0.     1.     0.875  2.625] |=| 5.749999999999999
[ 0.    0.    0.25 -9.25] |=| -37.5
[  0.     0.     4.25 -20.25] |=| -89.49999999999999
----------------
[ 1.          0.66666667  1.33333333 -1.        ] |=| -12.666666666666666
[-0.     1.     0.875  2.625] |=| 5.749999999999999
[  0.   0.   1. -37.] |=| -150.0
[  0.   0.   0. 137.] |=| 548.0
----------------
Найденные корни:


[-4.0, -3.0, -2.0, 4.0]

In [18]:
Gauss_method(A2, B2)

[ 1.   1.5 -0.5  2.   0.5] |=| -12.5
[ 0.  1. -2. -9.  1.] |=| 57.0
[ 0. -3. -1. -7.  2.] |=| 55.0
[ 0.   0.5 -2.5  5.   5.5] |=| -60.5
[  0.  -8.   3. -11.  -6.] |=| 34.0
----------------
[ 1.   1.5 -0.5  2.   0.5] |=| -12.5
[ 0.  1. -2. -9.  1.] |=| 57.0
[  0.   0.  -7. -34.   5.] |=| 226.0
[ 0.   0.  -1.5  9.5  5. ] |=| -89.0
[  0.   0. -13. -83.   2.] |=| 490.0
----------------
[ 1.   1.5 -0.5  2.   0.5] |=| -12.5
[ 0.  1. -2. -9.  1.] |=| 57.0
[-0.         -0.          1.          4.85714286 -0.71428571] |=| -32.285714285714285
[ 0.          0.          0.         16.78571429  3.92857143] |=| -137.42857142857144
[  0.           0.           0.         -19.85714286  -7.28571429] |=| 70.28571428571428
----------------
[ 1.   1.5 -0.5  2.   0.5] |=| -12.5
[ 0.  1. -2. -9.  1.] |=| 57.0
[-0.         -0.          1.          4.85714286 -0.71428571] |=| -32.285714285714285
[0.         0.         0.         1.         0.23404255] |=| -8.187234042553193
[ 0.          0.          0.       

[10.0, 18.0, 70.0, -16.0, 35.0]